#!/usr/bin/env node
/**
 * generate-rss.mjs
 *
 * Generates public/rss.xml from content/blog/*.mdx (or .md) files.
 *
 * Usage:
 *   node scripts/generate-rss.mjs
 *   npm run generate:rss
 *
 * Runs automatically via "prebuild" hook before every production build.
 * Also triggered by watch-rss.mjs in dev mode.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const BLOG_DIR = path.join(ROOT, "content", "blog");
const OUTPUT = path.join(ROOT, "public", "rss.xml");
const BASE_URL = "https://carlosazaustre.es";
const MAX_ITEMS = 50;

// ─── Minimal frontmatter parser (no dependency on gray-matter for portability)
function parseFrontmatter(raw) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return { data: {}, content: raw };

  const yamlBlock = match[1];
  const content = raw.slice(match[0].length).trim();
  const data = {};

  for (const line of yamlBlock.split(/\r?\n/)) {
    const colonIdx = line.indexOf(":");
    if (colonIdx === -1) continue;

    const key = line.slice(0, colonIdx).trim();
    let value = line.slice(colonIdx + 1).trim();

    // Remove surrounding quotes
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    // Parse inline YAML arrays: [a, b, c]
    if (value.startsWith("[") && value.endsWith("]")) {
      data[key] = value
        .slice(1, -1)
        .split(",")
        .map((v) => v.trim().replace(/^['"]|['"]$/g, ""))
        .filter(Boolean);
    } else {
      data[key] = value;
    }
  }

  return { data, content };
}

function extractExcerpt(content, maxLength = 200) {
  const clean = content
    .replace(/!\[.*?\]\(.*?\)/g, "")
    .replace(/\[([^\]]+)\]\(.*?\)/g, "$1")
    .replace(/#{1,6}\s+/g, "")
    .replace(/`{1,3}[\s\S]*?`{1,3}/g, "")
    .replace(/\*{1,2}([^*]+)\*{1,2}/g, "$1")
    .replace(/_{1,2}([^_]+)_{1,2}/g, "$1")
    .replace(/<[^>]+>/g, "")
    .replace(/\n+/g, " ")
    .trim();

  if (clean.length <= maxLength) return clean;
  const cut = clean.lastIndexOf(" ", maxLength);
  return clean.slice(0, cut > 0 ? cut : maxLength) + "…";
}

function escapeXml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function buildRss(posts) {
  const lastBuildDate =
    posts.length > 0
      ? new Date(posts[0].date).toUTCString()
      : new Date().toUTCString();

  const items = posts
    .slice(0, MAX_ITEMS)
    .map(({ slug, title, date, excerpt, tags }) => {
      const url = `${BASE_URL}/blog/${slug}`;
      const pubDate = new Date(date).toUTCString();
      const cats = (Array.isArray(tags) ? tags : [])
        .map((t) => `    <category>${escapeXml(t)}</category>`)
        .join("\n");

      return `  <item>
    <title>${escapeXml(title)}</title>
    <link>${url}</link>
    <guid isPermaLink="true">${url}</guid>
    <description>${escapeXml(excerpt)}</description>
    <pubDate>${pubDate}</pubDate>
${cats}
  </item>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-rss.mjs — do not edit manually -->
<rss version="2.0"
  xmlns:atom="http://www.w3.org/2005/Atom"
  xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Carlos Azaustre — Blog</title>
    <link>${BASE_URL}/blog</link>
    <description>Artículos sobre JavaScript, React, Node.js, arquitectura de software e inteligencia artificial.</description>
    <language>es</language>
    <lastBuildDate>${lastBuildDate}</lastBuildDate>
    <atom:link href="${BASE_URL}/rss.xml" rel="self" type="application/rss+xml"/>
    <image>
      <url>${BASE_URL}/carlos-azaustre.jpg</url>
      <title>Carlos Azaustre — Blog</title>
      <link>${BASE_URL}/blog</link>
    </image>
    <copyright>© ${new Date().getFullYear()} Carlos Azaustre</copyright>
    <managingEditor>cazaustre@gmail.com (Carlos Azaustre)</managingEditor>
${items}
  </channel>
</rss>`;
}

function run() {
  if (!fs.existsSync(BLOG_DIR)) {
    console.error(`❌  Blog dir not found: ${BLOG_DIR}`);
    process.exit(1);
  }

  const files = fs
    .readdirSync(BLOG_DIR)
    .filter((f) => f.endsWith(".md") || f.endsWith(".mdx"));

  const posts = files
    .map((filename) => {
      const slug = filename.replace(/\.(md|mdx)$/, "");
      const raw = fs.readFileSync(path.join(BLOG_DIR, filename), "utf8");
      const { data, content } = parseFrontmatter(raw);

      return {
        slug,
        title: data.title ?? "Sin título",
        date: data.date ? String(data.date) : "1970-01-01",
        excerpt: data.excerpt ?? extractExcerpt(content),
        tags: Array.isArray(data.tags) ? data.tags : [],
      };
    })
    .filter((p) => p.date && !isNaN(new Date(p.date).getTime()))
    .sort((a, b) => new Date(b.date) - new Date(a.date));

  const xml = buildRss(posts);

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, xml, "utf8");

  console.log(`✅  RSS generado → public/rss.xml  (${posts.length} posts, ${Math.round(xml.length / 1024)} KB)`);
}

run();
